---
- name: Update system
  apt:
    update_cache: yes
    upgrade: dist

- name: Install base packages
  apt:
    name:
      - curl
      - vim
      - net-tools
    state: present
    update_cache: yes