---
# Wait for hosts
- name: Wait for all hosts
  hosts: all
  gather_facts: false
  tasks:
    - wait_for_connection:
        timeout: 300
# K3s master FIRST
- name: Setup K3s master
  hosts: k3s_server
  become: true
  roles:
    - k3s_master

# Workers AFTER master
- name: Setup K3s workers
  hosts: k3s_workers
  become: true
  roles:
    - k3s_worker